### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by kraetos10** [edonv/CollectionView#1]
Works looks great but we need some examples of how to use - even if it’s a basic example to build off of.

**Comment by edonv** [comment]
Sorry for the huge delay on getting back to you! I'm not sure when I'll have the time to write out examples in a ton of detail, but I have a few "examples" I wrote out for testing purposes in the package. They can be found [here](https://github.com/edonv/CollectionView/tree/3d98734e19b9b660081b5e8573827b20b3dcd8c2/Sources/CollectionView/Testing).

I'm going to close this issue, but when I do get around to writing some detailed examples, I'll comment here or something to let you know!
